<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  /*
  * 模拟第一次发送网络请求，得到 aaa
  * 第二次自己处理成 aaa111
  * 第三次自己处理成 aaa111222
  * */

  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('aaa')
    }, 1000)
  }).then((res) => {
    console.log(res, '第一层自己处理的10行代码');

    return new Promise((resolve) => {
      resolve(res + '111')
    })
  }).then((res) => {
    console.log(res, '第二层自己处理的10行代码');

    return new Promise((resolve, reject) => {
      resolve(res + '222')
    })
  }).then(res => {
    console.log(res, '第三层自己处理的10行代码');
  })

  //  简写方式
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('aaa')
    }, 1000)
  }).then((res) => {
    console.log(res, '第一层自己处理的10行代码');

    // return new Promise((resolve) => {
    //   resolve(res + '111')
    // })
    return Promise.resolve(res + '111')
  }).then((res) => {
    console.log(res, '第二层自己处理的10行代码');

    // return new Promise((resolve, reject) => {
    //   resolve(res + '222')
    // })
    return Promise.resolve(res + '222')
  }).then(res => {
    console.log(res, '第三层自己处理的10行代码');
  })

  //再次简写方式
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('aaa')
    }, 1000)
  }).then((res) => {
    console.log(res, '第一层自己处理的10行代码');

    // return new Promise((resolve) => {
    //   resolve(res + '111')
    // })

    //return Promise.resolve(res + '111')
    return res + '1111'
  }).then((res) => {
    console.log(res, '第二层自己处理的10行代码');

    // return new Promise((resolve, reject) => {
    //   resolve(res + '222')
    // })

    //return Promise.resolve(res + '222')
    return res + '2222'
  }).then(res => {
    console.log(res, '第三层自己处理的10行代码');
  })

  //如果有reject或者异常
  new Promise((resolve) => {
    setTimeout(() => {
      resolve('aaa')
    }, 1000)
  }).then((res) => {
    console.log(res, '第一层自己处理的10行代码');

    return res + '1111'
  }).then((res) => {
    console.log(res, '第二层自己处理的10行代码');

    return Promise.reject('error message')
  }).then(res => {
    console.log(res, '第三层自己处理的10行代码');
  }).catch(err =>{
    console.log(err,'发生异常');
  })
</script>
</body>
</html>